name: helloworld
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  get: ^4.6.6
  web3dart: ^2.7.3
  web_socket_channel: ^3.0.2
  provider: ^6.1.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/Images/adminlogo.jpg"

flutter:
  uses-material-design: true
  assets:
   - lib/Images/adminlogo.jpg
   - lib/components/
   - assets/BloodLink.json
   - E:/temp flutter/final_year_project/smartcontract/build/contracts/BloodLink.json
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
